# Generated by Django 2.0.7 on 2018-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.CharField(blank=True, max_length=50, verbose_name='флаг продукта'),
        ),
    ]
